name: Build Windows App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: pyinstaller --onefile --windowed app.py

    - name: Install Inno Setup
      run: choco install innosetup --yes

    - name: Build Installer
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" setup.iss
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Installer
        path: Output/
